### ISSUE TITLE
USER STORY <Change Password>

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/PP4_redemption_website#14]
As a **logged-in user**, I can **change my password from my Profile page** so that **I can update my security information if needed**.

### Acceptance Criteria:
- [ ] User can enter their current and new password.
- [ ] System validates the current and the new password.
- [ ] Confirmation message displays upon successful password change.

### Tasks:
- [ ] Add password fields for current and new one.
- [ ] Implement backend logic for password verification and update.
- [ ] Display confirmation message.
- [ ] Test password change with correct and incorrect current password.
