### ISSUE TITLE
USER STORY <Browse Available Rewards>

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/PP4_redemption_website#16]
As a **user**, I can **access to the list of available rewards (gift cards)** so that **I know what I can redeem my points for and view details for each reward**.

### Acceptance Criteria:
- [ ] Rewards catalogue displays all available gift cards in a grid or list format.
- [ ] Each reward shows key information at a glance (points, brand name, image).
- [ ] User can access more information for each gift card by clicking a "View Details" link.
- [ ] Details page displays additional information for each gift card (full description, points required, image, T&Cs) and a redeem button.

### Tasks:
- [ ] Design catalogue layout with a grid or list format.
- [ ] Implement backend logic to retrieve the available gift cards and display them in the catalogue.
- [ ] Add "View Details" link to each gift cards to access individual page.
- [ ] Design details page layout to display full description, larger image, points required, T&Cs, redeem button.
- [ ] Implement backend logic to retrieve and display detailed information for selected gift card.
- [ ] Test navigation between catalogue and details page to ensure a smooth flow.
