### ISSUE TITLE
USER STORY <Add Rewards to cart>

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/PP4_redemption_website#17]
As a **user**, I can **add rewards to a cart** so that **I can review my selected gift cards before redeeming my points**.

### Acceptance Criteria:
- [ ] User can access to a "Add to cart" button for each item in the catalogue.
- [ ] Clicking "Add to cart" adds the new gift card to the user's selection.
- [ ] If the user's point balance is insufficient, the "Add to cart" button is disabled and alert is displayed.
- [ ] User can see the total points needed in the cart.

### Tasks:
- [ ] Implement a "Add to cart" button on rewards in the catalogue.
- [ ] Diplay a cart icon that shows total points needed for redemption aside with points balance.
- [ ] Implement backend logic to store items added to the cart for the current session.
- [ ] Test the "Add to cart" button functionality for each item in the catalogue.
- [ ] Verufy that the cart icon updates correctly with total points displaying.
