### ISSUE TITLE
USER STORY <Admin - Add new gift card>

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/PP4_redemption_website#19]
As an **admin**, I can **add  new gift card to the catalogue** so that **I can improve the offering available to users**.

### Acceptance Criteria:
- [ ] Admin can access the data-model table that displays existing gift cards.
- [ ] Admin can add a new row to the table to input details of the new item.
- [ ] Required fields (name, points, etc.) are validated before saving.
- [ ] New gift card appears in the catalogue.

### Tasks:
- [ ] Allow admins to add a new row in the table for entering new gift card information.
- [ ] Implement field validation to ensure required fields are completed.
- [ ] Save the new gift card to the database and update the catalog in real-time.
- [ ] Test adding a new reward, validation, and catalog update.
