### ISSUE TITLE
USER STORY <Admin - Edit Existing Reward>

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/PP4_redemption_website#20]
As an **admin**, I can **edit gift card details in the data-model** so that **I can keep information current and make update as needed**.

### Acceptance Criteria:
- [ ] Admin can edit and modify  gift cards details in the data-model. 
- [ ] Updated information is visible to users immediately.

### Tasks:
- [ ] Allow admins to edit the gift cards information in the data-model.
- [ ] Save the update to the database and the catalog in real-time.
- [ ] Test modifying gift cards details, validation, and catalog update.
