### ISSUE TITLE
USER STORY <Admin - Delete Reward>

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/PP4_redemption_website#21]
As a **admin**, I can **delete a reward from the catalogue** so that **users only see active and available items.**.

### Acceptance Criteria:
- [ ] Admin can delete items in the catalogue.
- [ ] Deleted items are removed from the catalogue and no longer visible to users.

### Tasks:
- [ ] Remove the reward from the data-model table and update the catalog view for users.
- [ ]  Test deletion to ensure the item is removed and no longer visible to users.
