### ISSUE TITLE
USER STORY <Admin - Manage Employee Points Balance>

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/PP4_redemption_website#22]
As an **admin**, I can **view, add, and adjust an employee’s points balance** so that ** I can ensure their balance is accurate and reflects any awards or adjustments**.

### Acceptance Criteria:
- [ ] Admin can access a data-model table displaying each employee’s name, ID and current points balance.
- [ ] Admin can search for an employee's name or ID in the data-model.
- [ ] Admin can view an employee’s points balance.
- [ ] Admin can adjust (increase or decrease) an employee’s balance as needed.
- [ ] Admin sees real-time updates or a confirmation message upon successfully modifying a balance.

### Tasks:
- [ ] Implement search functionality, by employee's name or ID.
- [ ] Implement backend logic to retrieve and display employee's current points balance.
- [ ] Implement an input field or button to adjust (increase or decrease) an employee’s balance directly in the table.
- [ ] Test points addition or suppression with udpate in real-time.
